# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 7

platform:
  - x86
  - x64

matrix:
  fast_finish: true

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install

test_script:
  - npm test

cache:
  # global npm cache
  - '%APPDATA%\\npm-cache'

  # global Yarn cache
  - "%LOCALAPPDATA%\\Yarn"
